name: deploy-book

# Only run this when the master branch changes
on:
  workflow_dispatch:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1' # The R version to download (if necessary) and use.
    - run: Rscript -e "install.packages('IRkernel')"
    - run: Rscript -e "install.packages('tidyverse')"
    - run: Rscript -e "install.packages('ggrepel')"
    - run: Rscript -e "IRkernel::installspec()"
  
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .
        
    # Push to server
    - name: rsync and ssh
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_DIR: ${{ secrets.REMOTE_TARGET }}
        LOCAL_DIR: "_build/html/"
        COURSE_NAME: "data551"
        TERM: "2021_WT2"
      run: |
        mkdir ~/.ssh
        echo "$REMOTE_KEY" > ~/.ssh/id_rsa
        ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
        rsync -avzr --delete $LOCAL_DIR $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/courses/$COURSE_NAME/$TERM
